name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test
    - name: Package-app
      run: |
        mkdir package
        cp ./target/release/ins-tracer package
        tar zcf ins-tracer.tar.gz ./package/*
    - name: upload-app-artifact
      uses: actions/upload-artifact@v4
      with:
        name: ins-tracer-artifact
        path: ins-tracer.tar.gz
        
